// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB0OGiS2m8tXntqwCsNXz_t6MsVDzokfs',
    appId: '1:188165506011:web:0345ad93d127d17122ddfe',
    messagingSenderId: '188165506011',
    projectId: 'fotos-cd61e',
    authDomain: 'fotos-cd61e.firebaseapp.com',
    storageBucket: 'fotos-cd61e.appspot.com',
    measurementId: 'G-7KJK3MKYJD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuwubA2hUM0WJW92M2MeYW_ImS7-K84nY',
    appId: '1:188165506011:android:0ed16d8ce751aa7d22ddfe',
    messagingSenderId: '188165506011',
    projectId: 'fotos-cd61e',
    storageBucket: 'fotos-cd61e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaduwKZ49URBaYeTTY5undhyrOSCrbWNY',
    appId: '1:188165506011:ios:6cc8dcd6a8b7f08122ddfe',
    messagingSenderId: '188165506011',
    projectId: 'fotos-cd61e',
    storageBucket: 'fotos-cd61e.appspot.com',
    iosBundleId: 'com.example.fotos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaduwKZ49URBaYeTTY5undhyrOSCrbWNY',
    appId: '1:188165506011:ios:6cc8dcd6a8b7f08122ddfe',
    messagingSenderId: '188165506011',
    projectId: 'fotos-cd61e',
    storageBucket: 'fotos-cd61e.appspot.com',
    iosBundleId: 'com.example.fotos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDB0OGiS2m8tXntqwCsNXz_t6MsVDzokfs',
    appId: '1:188165506011:web:b5b9dd100d005e1422ddfe',
    messagingSenderId: '188165506011',
    projectId: 'fotos-cd61e',
    authDomain: 'fotos-cd61e.firebaseapp.com',
    storageBucket: 'fotos-cd61e.appspot.com',
    measurementId: 'G-3RJLW49R76',
  );
}
